version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
          working_directory: ./CI-project

      - run:
            name: Install Tenderly CLI
            command: curl https://raw.githubusercontent.com/Tenderly/tenderly-cli/master/scripts/install-linux.sh | sudo sh

      - run:
          name: Run Tests
          command: yarn run test:devnet
          working_directory: ./CI-project

workflows:
  version: 2
  build-deploy:
    jobs:
      - build